server:
  port: 8888
  
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iblog
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    

---

spring:
  profiles: dev
  thymeleaf:
    cache: false
    
---

spring:
  profiles: prod
  thymeleaf:
    cache: true
